  
- hosts: all
  tasks:
   
   - name: "copy hadoop software"
     copy:
          src: "/root/hadoop-1.2.1-1.x86_64.rpm"
          dest: "/root/hadoop-1.2.1-1.x86_64.rpm"

   - name: "copy jdk software"
     copy:
          src: "/root/jdk-8u171-linux-x64.rpm"
          dest: "/root/jdk-8u171-linux-x64.rpm"
  
   - name: "install  jdk software"
     command:
        cmd: "rpm -ih jdk-8u171-linux-x64.rpm "
  

   - name: "install  hadoop software"
     command
        cmd: "rpm -ih hadoop-1.2.1-1.x86_64.rpm --force"
 
- hosts: namenode 
  vars:
  - ip: 192.168.0.111
  
  tasks:
  - name: "create directory"
    file:
            path: /nn
            state: directory

  - name: "configure hdfs-site.xml file"
    blockinfile:
      path: "/etc/hadoop/hdfs-site.xml"
      insertafter: "<configuration>"
      block:
              <property>
              <name>dfs.name.dir</name>
              <value>/nn</value>
              </property>
  - name: "configure core-site.xml file"
    blockinfile:
      path: "/etc/hadoop/core-site.xml"
      insertafter: "<configuration>"
      block:
              <property>
              <name>fs.default.name</name>
              <value>hdfs://{{ ip }}:9001</value>
              </property>


  - shell: "echo Y | hadoop namenode -format"
    ignore_errors: true
  - selinux:
          state: disabled

  - name: "stop firewalld"
    shell: "systemctl stop firewalld"


  - name: "start namenode"
    shell: "hadoop-daemon.sh start namenode"
    ignore_errors: true

  

  - name: "jps"
    shell: "jps"

- hosts: datanode

  vars:
  - ip: 192.168.0.111

  
  tasks:
  - name: "create directory"
    file:
            path: /dn
            state: directory


  - name: "configure hdfs-site.xml file"
    blockinfile:
      path: "/etc/hadoop/hdfs-site.xml"
      insertafter: "<configuration>"
      block:
              <property>
              <name>dfs.data.dir</name>
              <value>/dn</value>
              </property>
  - name: "configure core-site.xml file"
    blockinfile:
      path: "/etc/hadoop/core-site.xml"
      insertafter: "<configuration>"
      block:
              <property>
              <name>fs.default.name</name>
              <value>hdfs://{{ ip }}:9001</value>
              </property>

  - selinux:
          state: disabled

  - name: "stop firewalld"
    shell: "systemctl stop firewalld"
  
  - name: "stop datanode"
    shell: "hadoop-daemon.sh  stop datanode"
    ignore_errors: true

  - name: "start datanode"
    shell: "hadoop-daemon.sh start datanode"
    ignore_errors: true


  - name: "jps"
    shell: "jps"